const testActList = [
    {
        "id": "act18d0",
        "name": "遗尘漫步",
        "type": "TYPE_ACT9D0",
        "endTime": 1619639999,
        "hasStage": true,
        "startTime": 1618459200,
        "displayType": "BRANCHLINE",
        "isReplicate": false,
        "medalGroupId": "medalGroupActivity18d0",
        "actTopBarText": null,
        "displayOnHome": true,
        "rewardEndTime": 1620244799,
        "actTopBarColor": null,
        "templateShopId": "shop_act18d0"
    },
    {
        "id": "act16d5d1",
        "name": "登录领取奖励",
        "type": "LOGIN_ONLY",
        "endTime": 1613678399,
        "hasStage": false,
        "startTime": 1612512000,
        "isReplicate": false,
        "medalGroupId": null,
        "actTopBarText": "新春限时登录活动",
        "displayOnHome": false,
        "rewardEndTime": 1613678399,
        "actTopBarColor": "2ebf81",
        "templateShopId": null
    },
    {
        "id": "act17d0",
        "name": "源石尘行动",
        "type": "TYPE_ACT9D0",
        "endTime": 1616443199,
        "hasStage": true,
        "startTime": 1615262400,
        "isReplicate": false,
        "medalGroupId": null,
        "actTopBarText": null,
        "displayOnHome": true,
        "rewardEndTime": 1617047999,
        "actTopBarColor": null,
        "templateShopId": "shop_act17d0"
    },
    {
        "id": "act16d6",
        "name": "限时累计签到",
        "type": "CHECKIN_ONLY",
        "endTime": 1614887999,
        "hasStage": false,
        "startTime": 1613073600,
        "isReplicate": false,
        "medalGroupId": null,
        "actTopBarText": "岁暮点雪签到活动",
        "displayOnHome": false,
        "rewardEndTime": 1614887999,
        "actTopBarColor": "2719fa",
        "templateShopId": null
    },
    {
        "id": "act16d5",
        "name": "画中人",
        "type": "TYPE_ACT9D0",
        "endTime": 1613678399,
        "hasStage": true,
        "startTime": 1612512000,
        "isReplicate": false,
        "medalGroupId": "medalGroupActivity16d5",
        "actTopBarText": null,
        "displayOnHome": true,
        "rewardEndTime": 1614283199,
        "actTopBarColor": null,
        "templateShopId": "shop_act16d5"
    },
    {
        "id": "act15d5",
        "name": "此地之外",
        "type": "MINISTORY",
        "endTime": 1610395199,
        "hasStage": true,
        "startTime": 1609833600,
        "isReplicate": false,
        "medalGroupId": null,
        "actTopBarText": null,
        "displayOnHome": true,
        "rewardEndTime": 1610654399,
        "actTopBarColor": null,
        "templateShopId": "shop_act15d5"
    },
    {
        "id": "act17d1",
        "name": "罗德岛防御协议",
        "type": "MULTIPLAY",
        "endTime": 1616443199,
        "hasStage": true,
        "startTime": 1615262400,
        "isReplicate": false,
        "medalGroupId": null,
        "actTopBarText": null,
        "displayOnHome": true,
        "rewardEndTime": 1617047999,
        "actTopBarColor": null,
        "templateShopId": null
    },
    {
        "id": "act17d7",
        "name": "愚人节活动",
        "type": "TYPE_ACT17D7",
        "endTime": 1617825599,
        "hasStage": false,
        "startTime": 1617264000,
        "isReplicate": false,
        "medalGroupId": null,
        "actTopBarText": "泰拉\\n说唱之夜！",
        "displayOnHome": false,
        "rewardEndTime": 1617825599,
        "actTopBarColor": "ff7e00",
        "templateShopId": null
    },
    {
        "id": "act17d5",
        "name": "生于黑夜·复刻",
        "type": "TYPE_ACT9D0",
        "endTime": 1617911999,
        "hasStage": true,
        "startTime": 1617091200,
        "displayType": "BRANCHLINE",
        "isReplicate": true,
        "medalGroupId": null,
        "actTopBarText": null,
        "displayOnHome": true,
        "rewardEndTime": 1618257599,
        "actTopBarColor": null,
        "templateShopId": "shop_act17d5"
    },
    {
        "id": "act17d0d1",
        "name": "限时累计签到",
        "type": "CHECKIN_ONLY",
        "endTime": 1616443199,
        "hasStage": false,
        "startTime": 1615262400,
        "isReplicate": false,
        "medalGroupId": null,
        "actTopBarText": "锋芒将现签到活动",
        "displayOnHome": false,
        "rewardEndTime": 1616443199,
        "actTopBarColor": "e16919",
        "templateShopId": null
    },
    {
        "id": "act17d0d2",
        "name": "登录领取奖励",
        "type": "LOGIN_ONLY",
        "endTime": 1616443199,
        "hasStage": false,
        "startTime": 1615262400,
        "isReplicate": false,
        "medalGroupId": null,
        "actTopBarText": "联动限时登录活动",
        "displayOnHome": false,
        "rewardEndTime": 1616443199,
        "actTopBarColor": "ffae00",
        "templateShopId": null
    },
    {
        "id": "act16d5d2",
        "name": "龙门幸运墙登录活动",
        "type": "PRAY_ONLY",
        "endTime": 1613678399,
        "hasStage": false,
        "startTime": 1612512000,
        "isReplicate": false,
        "medalGroupId": null,
        "actTopBarText": "幸运墙登录活动",
        "displayOnHome": false,
        "rewardEndTime": 1613678399,
        "actTopBarColor": "df462d",
        "templateShopId": null
    },
    {
        "id": "act15d1",
        "name": "跨年限时登录活动",
        "type": "CHECKIN_ONLY",
        "endTime": 1609963199,
        "hasStage": false,
        "startTime": 1608753600,
        "isReplicate": false,
        "medalGroupId": null,
        "actTopBarText": "跨年限时登录活动",
        "displayOnHome": false,
        "rewardEndTime": 1609963199,
        "actTopBarColor": "f92946",
        "templateShopId": null
    },
    {
        "id": "act15d0",
        "name": "孤岛风云",
        "type": "TYPE_ACT9D0",
        "endTime": 1609358399,
        "hasStage": true,
        "startTime": 1608177600,
        "isReplicate": false,
        "medalGroupId": "medalGroupActivity15d0",
        "actTopBarText": null,
        "displayOnHome": true,
        "rewardEndTime": 1609963199,
        "actTopBarColor": null,
        "templateShopId": "shop_act15d0"
    },
    {
        "id": "act14d7",
        "name": "喧闹法则·复刻",
        "type": "TYPE_ACT5D0",
        "endTime": 1607630399,
        "hasStage": true,
        "startTime": 1606809600,
        "isReplicate": true,
        "medalGroupId": null,
        "actTopBarText": null,
        "displayOnHome": true,
        "rewardEndTime": 1607975999,
        "actTopBarColor": null,
        "templateShopId": null
    },
    {
        "id": "act14d0d2",
        "name": "登录领取奖励",
        "type": "LOGIN_ONLY",
        "endTime": 1605383999,
        "hasStage": false,
        "startTime": 1604203200,
        "isReplicate": false,
        "medalGroupId": null,
        "actTopBarText": "感谢庆典登录活动",
        "displayOnHome": false,
        "rewardEndTime": 1605383999,
        "actTopBarColor": "538cff",
        "templateShopId": null
    },
    {
        "id": "act13d2d2",
        "name": "骑兵与猎人复刻签到",
        "type": "CHECKIN_ONLY",
        "endTime": 1602359999,
        "hasStage": false,
        "startTime": 1601582400,
        "isReplicate": false,
        "medalGroupId": null,
        "actTopBarText": "猎人补给进行中",
        "displayOnHome": false,
        "rewardEndTime": 1602359999,
        "actTopBarColor": "467997",
        "templateShopId": null
    },
    {
        "id": "act13d2",
        "name": "骑兵与猎人·复刻",
        "type": "TYPE_ACT9D0",
        "endTime": 1602359999,
        "hasStage": true,
        "startTime": 1601539200,
        "isReplicate": true,
        "medalGroupId": null,
        "actTopBarText": null,
        "displayOnHome": true,
        "rewardEndTime": 1602705599,
        "actTopBarColor": null,
        "templateShopId": "shop_act13d2"
    },
    {
        "id": "act14d0d1",
        "name": "限时累计签到",
        "type": "CHECKIN_ONLY",
        "endTime": 1605383999,
        "hasStage": false,
        "startTime": 1604203200,
        "isReplicate": false,
        "medalGroupId": null,
        "actTopBarText": "感谢庆典签到活动",
        "displayOnHome": false,
        "rewardEndTime": 1605383999,
        "actTopBarColor": "ff6425",
        "templateShopId": null
    },
    {
        "id": "act13d5",
        "name": "玛莉娅·临光",
        "type": "TYPE_ACT9D0",
        "endTime": 1603915199,
        "hasStage": true,
        "startTime": 1602748800,
        "isReplicate": false,
        "medalGroupId": "medalGroupActivity13d5",
        "actTopBarText": null,
        "displayOnHome": true,
        "rewardEndTime": 1604519999,
        "actTopBarColor": null,
        "templateShopId": "shop_act13d5"
    },
    {
        "id": "act13d2d1",
        "name": "限时累计签到",
        "type": "CHECKIN_ONLY",
        "endTime": 1602359999,
        "hasStage": false,
        "startTime": 1601496000,
        "isReplicate": false,
        "medalGroupId": null,
        "actTopBarText": "限时活动进行中",
        "displayOnHome": false,
        "rewardEndTime": 1602359999,
        "actTopBarColor": "f49c49",
        "templateShopId": null
    },
    {
        "id": "act13d0",
        "name": "踏寻往昔之风",
        "type": "MINISTORY",
        "endTime": 1601495999,
        "hasStage": true,
        "startTime": 1600920000,
        "isReplicate": false,
        "medalGroupId": null,
        "actTopBarText": null,
        "displayOnHome": true,
        "rewardEndTime": 1601755199,
        "actTopBarColor": null,
        "templateShopId": "shop_act13d0"
    },
    {
        "id": "act12d0",
        "name": "密林悍将归来",
        "type": "TYPE_ACT9D0",
        "endTime": 1599508799,
        "hasStage": true,
        "startTime": 1598328000,
        "isReplicate": false,
        "medalGroupId": "medalGroupActivity12d0",
        "actTopBarText": null,
        "displayOnHome": true,
        "rewardEndTime": 1600113599,
        "actTopBarColor": null,
        "templateShopId": "shop_act12d0"
    },
    {
        "id": "act12d6",
        "name": "刻俄柏的灰蕈迷境",
        "type": "ROGUELIKE",
        "endTime": 1600113599,
        "hasStage": true,
        "startTime": 1598328000,
        "isReplicate": false,
        "medalGroupId": null,
        "actTopBarText": null,
        "displayOnHome": true,
        "rewardEndTime": 1600718399,
        "actTopBarColor": null,
        "templateShopId": null
    },
    {
        "id": "act10d6",
        "name": "限时累计签到",
        "type": "CHECKIN_ONLY",
        "endTime": 1593892799,
        "hasStage": false,
        "startTime": 1593028800,
        "isReplicate": false,
        "medalGroupId": null,
        "actTopBarText": "限时活动进行中",
        "displayOnHome": false,
        "rewardEndTime": 1593892799,
        "actTopBarColor": "4adac4",
        "templateShopId": null
    },
    {
        "id": "act11d7",
        "name": "火蓝之心·复刻",
        "type": "TYPE_ACT3D0",
        "endTime": 1597953599,
        "hasStage": true,
        "startTime": 1597132800,
        "isReplicate": true,
        "medalGroupId": null,
        "actTopBarText": null,
        "displayOnHome": true,
        "rewardEndTime": 1598299199,
        "actTopBarColor": null,
        "templateShopId": null
    },
    {
        "id": "act11d0",
        "name": "沃伦姆德的薄暮",
        "type": "TYPE_ACT9D0",
        "endTime": 1595447999,
        "hasStage": true,
        "startTime": 1594267200,
        "isReplicate": false,
        "medalGroupId": "medalGroupActivity11d0",
        "actTopBarText": null,
        "displayOnHome": true,
        "rewardEndTime": 1596052799,
        "actTopBarColor": null,
        "templateShopId": "shop_act11d0"
    },
    {
        "id": "act10d5",
        "name": "乌萨斯的孩子们",
        "type": "MINISTORY",
        "endTime": 1593028799,
        "hasStage": true,
        "startTime": 1592467200,
        "isReplicate": false,
        "medalGroupId": null,
        "actTopBarText": null,
        "displayOnHome": true,
        "rewardEndTime": 1593287999,
        "actTopBarColor": null,
        "templateShopId": "shop_act10d5"
    },
    {
        "id": "act9d4",
        "name": "限时积分任务",
        "type": "COLLECTION",
        "endTime": 1590695999,
        "hasStage": false,
        "startTime": 1589486400,
        "isReplicate": false,
        "medalGroupId": null,
        "actTopBarText": "周年庆典作战活动",
        "displayOnHome": false,
        "rewardEndTime": 1590695999,
        "actTopBarColor": "f46525",
        "templateShopId": null
    },
    {
        "id": "act9d1d2",
        "name": "登录领取奖励",
        "type": "LOGIN_ONLY",
        "endTime": 1589486399,
        "hasStage": false,
        "startTime": 1588316400,
        "isReplicate": false,
        "medalGroupId": null,
        "actTopBarText": "周年庆典登录活动",
        "displayOnHome": false,
        "rewardEndTime": 1589486399,
        "actTopBarColor": "ff0327",
        "templateShopId": null
    },
    {
        "id": "act9d1d1",
        "name": "限时累计签到",
        "type": "CHECKIN_ONLY",
        "endTime": 1590695999,
        "hasStage": false,
        "startTime": 1588276800,
        "isReplicate": false,
        "medalGroupId": null,
        "actTopBarText": "周年庆典签到活动",
        "displayOnHome": false,
        "rewardEndTime": 1590695999,
        "actTopBarColor": "337eb8",
        "templateShopId": null
    },
    {
        "id": "act9d0",
        "name": "生于黑夜",
        "type": "TYPE_ACT9D0",
        "endTime": 1589486399,
        "hasStage": true,
        "startTime": 1587441600,
        "isReplicate": false,
        "medalGroupId": null,
        "actTopBarText": null,
        "displayOnHome": true,
        "rewardEndTime": 1590091199,
        "actTopBarColor": null,
        "templateShopId": "shop_act9d0"
    },
    {
        "id": "act8d2",
        "name": "愚人节活动",
        "type": "AVG_ONLY",
        "endTime": 1588276799,
        "hasStage": false,
        "startTime": 1585728000,
        "isReplicate": false,
        "medalGroupId": null,
        "actTopBarText": null,
        "displayOnHome": false,
        "rewardEndTime": 1588276799,
        "actTopBarColor": null,
        "templateShopId": null
    },
    {
        "id": "act7d1",
        "name": "限时累计签到",
        "type": "CHECKIN_ONLY",
        "endTime": 1584388799,
        "hasStage": false,
        "startTime": 1583179200,
        "isReplicate": false,
        "medalGroupId": null,
        "actTopBarText": "限时活动进行中",
        "displayOnHome": false,
        "rewardEndTime": 1584388799,
        "actTopBarColor": "ffc000",
        "templateShopId": null
    },
    {
        "id": "act6d8",
        "name": "限时积分任务",
        "type": "COLLECTION",
        "endTime": 1582315199,
        "hasStage": false,
        "startTime": 1581105600,
        "isReplicate": false,
        "medalGroupId": null,
        "actTopBarText": "限时活动进行中",
        "displayOnHome": false,
        "rewardEndTime": 1582315199,
        "actTopBarColor": "ff4128",
        "templateShopId": null
    },
    {
        "id": "act7d5",
        "name": "午间逸话",
        "type": "TYPE_ACT4D0",
        "endTime": 1583179199,
        "hasStage": true,
        "startTime": 1582617600,
        "isReplicate": false,
        "medalGroupId": null,
        "actTopBarText": null,
        "displayOnHome": true,
        "rewardEndTime": 1583783999,
        "actTopBarColor": null,
        "templateShopId": null
    },
    {
        "id": "act6d7",
        "name": "限时累计签到",
        "type": "CHECKIN_ONLY",
        "endTime": 1581105599,
        "hasStage": false,
        "startTime": 1579896000,
        "isReplicate": false,
        "medalGroupId": null,
        "actTopBarText": "限时活动进行中",
        "displayOnHome": false,
        "rewardEndTime": 1581105599,
        "actTopBarColor": "cb2632",
        "templateShopId": null
    },
    {
        "id": "act6d0",
        "name": "限时累计签到",
        "type": "CHECKIN_ONLY",
        "endTime": 1578427199,
        "hasStage": false,
        "startTime": 1577217600,
        "isReplicate": false,
        "medalGroupId": null,
        "actTopBarText": "限时活动进行中",
        "displayOnHome": false,
        "rewardEndTime": 1578427199,
        "actTopBarColor": "006eb6",
        "templateShopId": null
    },
    {
        "id": "act6d5",
        "name": "洪炉示岁",
        "type": "TYPE_ACT4D0",
        "endTime": 1579118399,
        "hasStage": true,
        "startTime": 1578513600,
        "isReplicate": false,
        "medalGroupId": null,
        "actTopBarText": null,
        "displayOnHome": true,
        "rewardEndTime": 1579723199,
        "actTopBarColor": null,
        "templateShopId": null
    },
    {
        "id": "act5d0",
        "name": "喧闹法则",
        "type": "TYPE_ACT5D0",
        "endTime": 1575316799,
        "hasStage": true,
        "startTime": 1574150400,
        "isReplicate": false,
        "medalGroupId": null,
        "actTopBarText": null,
        "displayOnHome": true,
        "rewardEndTime": 1575921599,
        "actTopBarColor": null,
        "templateShopId": null
    },
    {
        "id": "act5d1",
        "name": "危机合约",
        "type": "TYPE_ACT5D1",
        "endTime": 1575316799,
        "hasStage": true,
        "startTime": 1574150400,
        "isReplicate": false,
        "medalGroupId": null,
        "actTopBarText": null,
        "displayOnHome": true,
        "rewardEndTime": 1575921599,
        "actTopBarColor": null,
        "templateShopId": null
    },
    {
        "id": "act4d5",
        "name": "限时积分任务",
        "type": "COLLECTION",
        "endTime": 1574625599,
        "hasStage": false,
        "startTime": 1573416000,
        "isReplicate": false,
        "medalGroupId": null,
        "actTopBarText": "限时活动进行中",
        "displayOnHome": false,
        "rewardEndTime": 1574625599,
        "actTopBarColor": "f86900",
        "templateShopId": null
    },
    {
        "id": "act4d0",
        "name": "战地秘闻",
        "type": "TYPE_ACT4D0",
        "endTime": 1571687999,
        "hasStage": true,
        "startTime": 1571126400,
        "isReplicate": false,
        "medalGroupId": null,
        "actTopBarText": null,
        "displayOnHome": true,
        "rewardEndTime": 1572292799,
        "actTopBarColor": null,
        "templateShopId": null
    },
    {
        "id": "act4d2",
        "name": "限时累计签到",
        "type": "CHECKIN_ONLY",
        "endTime": 1573329599,
        "hasStage": false,
        "startTime": 1572552000,
        "isReplicate": false,
        "medalGroupId": null,
        "actTopBarText": "限时活动进行中",
        "displayOnHome": false,
        "rewardEndTime": 1573329599,
        "actTopBarColor": "a778f8",
        "templateShopId": null
    },
    {
        "id": "act3d7",
        "name": "限时累计签到",
        "type": "CHECKIN_ONLY",
        "endTime": 1570737599,
        "hasStage": false,
        "startTime": 1569873600,
        "isReplicate": false,
        "medalGroupId": null,
        "actTopBarText": "限时活动进行中",
        "displayOnHome": false,
        "rewardEndTime": 1570737599,
        "actTopBarColor": "8d4268",
        "templateShopId": null
    },
    {
        "id": "act3d5",
        "name": "限时积分任务",
        "type": "COLLECTION",
        "endTime": 1569268799,
        "hasStage": false,
        "startTime": 1568059200,
        "isReplicate": false,
        "medalGroupId": null,
        "actTopBarText": "限时活动进行中",
        "displayOnHome": false,
        "rewardEndTime": 1569268799,
        "actTopBarColor": "003edc",
        "templateShopId": null
    },
    {
        "id": "act3d0",
        "name": "火蓝之心",
        "type": "TYPE_ACT3D0",
        "endTime": 1568059199,
        "hasStage": true,
        "startTime": 1566892800,
        "isReplicate": false,
        "medalGroupId": null,
        "actTopBarText": null,
        "displayOnHome": true,
        "rewardEndTime": 1568663999,
        "actTopBarColor": null,
        "templateShopId": null
    },
    {
        "id": "act2d8",
        "name": "限时累计签到",
        "type": "CHECKIN_ONLY",
        "endTime": 1566763199,
        "hasStage": false,
        "startTime": 1565812800,
        "isReplicate": false,
        "medalGroupId": null,
        "actTopBarText": "限时活动进行中",
        "displayOnHome": false,
        "rewardEndTime": 1566763199,
        "actTopBarColor": "00b7ee",
        "templateShopId": null
    },
    {
        "id": "act2d5",
        "name": "限时累计签到",
        "type": "CHECKIN_ONLY",
        "endTime": 1564948799,
        "hasStage": false,
        "startTime": 1563739200,
        "isReplicate": false,
        "medalGroupId": null,
        "actTopBarText": "限时活动进行中",
        "displayOnHome": false,
        "rewardEndTime": 1564948799,
        "actTopBarColor": "9e1f28",
        "templateShopId": null
    },
    {
        "id": "act1d5",
        "name": "限时累计签到",
        "type": "CHECKIN_ONLY",
        "endTime": 1563739199,
        "hasStage": false,
        "startTime": 1562659200,
        "isReplicate": false,
        "medalGroupId": null,
        "actTopBarText": "限时活动进行中",
        "displayOnHome": false,
        "rewardEndTime": 1563739199,
        "actTopBarColor": "7AAC0D",
        "templateShopId": null
    },
    {
        "id": "1stact",
        "name": "骑兵与猎人",
        "type": "DEFAULT",
        "endTime": 1560369599,
        "hasStage": true,
        "startTime": 1559181600,
        "isReplicate": false,
        "medalGroupId": null,
        "actTopBarText": null,
        "displayOnHome": true,
        "rewardEndTime": 1560974399,
        "actTopBarColor": null,
        "templateShopId": null
    },
    {
        "id": "0D5act",
        "name": "限时任务",
        "type": "MISSION_ONLY",
        "endTime": 1559159999,
        "hasStage": false,
        "startTime": 1558576800,
        "isReplicate": false,
        "medalGroupId": null,
        "actTopBarText": null,
        "displayOnHome": false,
        "rewardEndTime": 1559159999,
        "actTopBarColor": "FFD800",
        "templateShopId": null
    }
]

export {
    testActList
}