- date: 2021-12-30
  pics:
    - /ark/kkdy11.png
    - /ark/%E6%98%8E%E6%97%A5%E6%96%B9%E8%88%9Fkkdy.png
  pics_m:
    - /ark/kkdy.png
    - /ark/kkdy11.png
    - /ark/%E6%98%8E%E6%97%A5%E6%96%B9%E8%88%9Fkkdy.png
  text: 竟然接到了商单，想支持kkdy继续下去的话，可以点击上面看看<@act.missionTips>\n(要注册，邀请码填kkdy)</>\n直接支持可以点击关于里面有收款码，或者小程序搜kkdy（海珠店那个），直接点一个请od喝冷萃。
  link: 'http://mp.weixin.qq.com/s?__biz=Mzg3NDY0NjUzNg==&mid=100002319&idx=1&sn=5ae6f886858d74feb56a9b571ec97ab8&chksm=4eccd76879bb5e7e0c44226a2dcad8a1407f2bca9d8d56b01d60c5ce18e80fc63358a6d063c9#rd'
