let defaultConfig = require("tailwindcss/defaultConfig")

module.exports = {
  corePlugins: {
    divide: false,
    space: false,
    focusWithin: false,
    container: false,
    appearance: false,
    backgroundAttachment: true,
    backgroundColor: true,
    backgroundPosition: true,
    backgroundRepeat: true,
    backgroundSize: true,
    borderColor: true,
    borderRadius: true,
    borderStyle: true,
    borderWidth: true,
    boxShadow: true,
    cursor: false,
    display: true,
    flex: true,
    flexDirection: true,
    flexGrow: true,
    flexShrink: true,
    fontSize: true,
    flexWrap: true,
    float: false,
    fontFamily: true,
    fontSmoothing: true,
    fontStyle: true,
    fontWeight: true,
    height: true,
    inset: false,
    justifyContent: true,
    letterSpacing: true,
    lineHeight: true,
    margin: true,
    maxHeight: true,
    maxWidth: true,
    minHeight: true,
    minWidth: true,
    negativeMargin: true,
    objectFit: true,
    objectPosition: true,
    opacity: true,
    outline: false,
    overflow: true,
    padding: true,
    placeholderColor: false,
    pointerEvents: false,
    position: true,
    resize: true,
    stroke: false,
    tableLayout: false,
    textAlign: true,
    textColor: true,
    textDecoration: true,
    textTransform: true,
    userSelect: false,
    verticalAlign: true,
    visibility: true,
    whitespace: true,
    width: true,
    wordBreak: true,
    zIndex: true,
  },
  variants: {
    appearance: [],
    backgroundAttachment: [],
    backgroundColor: [],
    backgroundPosition: [],
    backgroundRepeat: [],
    backgroundSize: [],
    borderCollapse: [],
    borderColor: [],
    borderRadius: [],
    borderStyle: [],
    borderWidth: [],
    cursor: [],
    display: [],
    flexDirection: [],
    flexWrap: [],
    alignItems: [],
    alignSelf: [],
    justifyContent: [],
    alignContent: [],
    flex: [],
    flexGrow: [],
    flexShrink: [],
    order: [],
    float: [],
    fontFamily: [],
    fontWeight: [],
    height: [],
    lineHeight: [],
    listStylePosition: [],
    listStyleType: [],
    margin: [],
    maxHeight: [],
    maxWidth: [],
    minHeight: [],
    minWidth: [],
    negativeMargin: [],
    objectFit: [],
    objectPosition: [],
    opacity: [],
    outline: [],
    overflow: [],
    padding: [],
    pointerEvents: [],
    position: [],
    inset: [],
    resize: [],
    boxShadow: [],
    fill: [],
    stroke: [],
    tableLayout: [],
    textAlign: [],
    textColor: [],
    fontSize: [],
    fontStyle: [],
    textTransform: [],
    textDecoration: [],
    fontSmoothing: [],
    letterSpacing: [],
    userSelect: [],
    verticalAlign: [],
    visibility: [],
    whitespace: [],
    wordBreak: [],
    width: [],
    zIndex: [],
  },
  theme: {
    backgroundSize: {
      cover: "cover",
      contain: "contain",
    },
    borderRadius: {
      none: "0px",
      sm: "2px",
      default: "4px",
      lg: "8px",
      xl: "10px",
      "2xl": "12px",
      full: "9999px",
    },
    borderWidth: {
      default: "1px",
      px: "1px",
      0: "0px",
      2: "2px",
      4: "4px",
      8: "8px",
    },
    fontFamily: {
      sans: [
        "system-ui",
        "BlinkMacSystemFont",
        "-apple-system",
        "Segoe UI",
        "Roboto",
        "Oxygen",
        "Ubuntu",
        "Cantarell",
        "Fira Sans",
        "Droid Sans",
        "Helvetica Neue",
        "sans-serif",
      ],
      serif: [
        "Constantia",
        "Lucida Bright",
        "Lucidabright",
        "Lucida Serif",
        "Lucida",
        "DejaVu Serif",
        "Bitstream Vera Serif",
        "Liberation Serif",
        "Georgia",
        "serif",
      ],
      mono: [
        "Menlo",
        "Monaco",
        "Consolas",
        "Liberation Mono",
        "Courier New",
        "monospace",
      ],
    },
    fontSize: {
      xxs: "20px",
      xs: "24px",
      sm: "28px",
      base: "32px",
      lg: "36px",
      xl: "40px",
      "2xl": "48px",
      "3xl": "60px",
      "4xl": "72px",
      "5xl": "96px",
    },
    spacing: {
      px: "1px",
      0: "0px",
      1: "8px",
      2: "16px",
      3: "24px",
      "3_5": "28px",
      4: "32px",
      5: "40px",
      6: "48px",
      "6_5": "52px",
      7: "54px",
      8: "64px",
      10: "80px",
      // 11: "2.75px",
      // 12: "3px",
      // 14: "3.5px",
      // 16: "4px",
      // 20: "5px",
      // 24: "6px",
      // 28: "7px",
      // 30: "7.5px",
      // 32: "8px",
      // 36: "9px",
      // 40: "10px",
      // 48: "12px",
      // 56: "14px",
      // 60: "15px",
      // 64: "16px",
      // 72: "18px",
      // 76: "19px",
      // 80: "20px",
      // 84: "21px",
      // 88: "22px",
      // 92: "23px",
      // 96: "24px",
      // 100: "25px",
      // 120: "30px",
      // 130: "32.5px",
      // 140: "35px",
      // 160: "40px",
      // 180: "45px",
      // 200: "50px",
    },
    width: (theme) => ({
      auto: "auto",
      ...theme("spacing"),
      "1_2": "50%",
      "1_3": "33.333333%",
      "2_3": "66.666667%",
      "1_4": "25%",
      "2_4": "50%",
      "3_4": "75%",
      "1_5": "20%",
      "2_5": "40%",
      "3_5": "60%",
      "4_5": "80%",
      "1_6": "16.666667%",
      "2_6": "33.333333%",
      "3_6": "50%",
      "4_6": "66.666667%",
      "5_6": "83.333333%",
      "1_12": "8.333333%",
      "2_12": "16.666667%",
      "3_12": "25%",
      "4_12": "33.333333%",
      "5_12": "41.666667%",
      "6_12": "50%",
      "7_12": "58.333333%",
      "8_12": "66.666667%",
      "9_12": "75%",
      "10_12": "83.333333%",
      "11_12": "91.666667%",
      full: "100%",
      screen: "100vw",
    }),
    height: (theme) => ({
      auto: "auto",
      ...theme("width"),
      screen: "100vh",
    }),
    maxHeight: {
      full: "100%",
      screen: "100vh",
    },
    maxWidth: {
      xs: "4px",
      sm: "8px",
      md: "16px",
      lg: "32px",
      xl: "64px",
      "2xl": "128px",
      "3xl": "256px",
      "4xl": "512px",
      full: "100%",
    },
    darkMode: "class",
  },
}
